sudo: false
language: cpp
compiler:
  - clang
  - gcc
notifications:
  email:
    recipients:
      - jwbecher@drazisil.com
    on_success: change
    on_failure: change
addons:
  apt:
    packages:
    - python-wxgtk2.8 
    - python-wxtools wx2.8-i18n 
    - libwxgtk2.8-dev 
    - libgtk2.0-dev
before_script:
- "find src -type f -name *.h -exec sed -i 's/-e//g'"
